<?php
/**
 * Страница "Форма редактирования плагина".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Форма редактирования плагина</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/edit.png' ?>" />
    </div>
    <p>Форма редактирования плагина появляется после выбора пункта <b>"Редактировать"</b> контекстного меню выбранной записи.</p>
    <p>Для каждой вкладки, соответствующей определённому языку, заполняются соответствующие поля формы.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Название.</b> Название плагина;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Описание.</b> Описание плагина;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Доступен.</b> Видимость плагина в Панели управления или на сайте.</li>
    </ul>
</article>