<?php
/**
 * Страница "Форма редактирования плагина".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Plugin editing</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/edit.png' ?>" />
    </div>
    <p>The plugin editing form appears after selecting the <b>"Edit"</b> item from the context menu of the selected entry.</p>
    <p>For each tab corresponding to a specific language, the corresponding form fields are filled in.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Plugin name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> Plugin description;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Enabled.</b> Plugin visibility in the Control Panel or on the website.</li>
    </ul>
</article>