<?php
/**
 * Страница "Список плагинов".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Список плагинов</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>Список плагинов динамически формируется в соответствии с активным фильтром: отображаются либо установленные, либо не установленные плагины, либо обе категории.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Название.</b> Название, описание и версия плагина;</li>
        <li><b>Идентификатор.</b> Уникальный идентификатор плагина;</li>
        <li><b>Путь.</b> Локальный путь к установленному плагину;</li>
        <li><b>Автор.</b> Автор плагина;</li>
        <li><b>Версия.</b> Версия плагина;</li>
        <li><b>Доступность.</b> Доступ к плагину через Панель управления или сайт;</li>
        <li><b>Статус.</b> Статус плагина: установлен, не установлен, ошибка, неизвестно.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-install.svg' ?>" /> <b>Установить.</b> Вызывает форму для установки выбранного плагина из списка;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-uninstall.svg' ?>" /> <b>Удалить.</b> Полностью удаляет установленный плагин;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Удалить.</b> Удаляет пакет загруженного плагина;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-unmount.svg' ?>" /> <b>Демонтаж.</b> Удаляет (деинсталлирует) установленный плагин без удаления его из репозитория;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-download.svg' ?>" /> <b>Скачать.</b> Скачивает пакет плагина, соответствующий элементу, выделенному в списке;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-upload.svg' ?>" /> <b>Загрузить.</b> Загружает файл пакета плагина для дальнейшей установки;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызывает форму для редактирования плагина;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение плагинов в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список плагинов;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-update-config.svg' ?>" /> <b>Обновить.</b> Выполняет обновление конфигурации установленных плагинов. Используется при внесении изменений в файлы конфигурации плагинов или приложения;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о плагине;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать / Скрыть.</b> Показывает или скрывает столбцы, которые скрыты по умолчанию;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Вызывает форму поиска плагинов в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Фильтр.</b> Выполняет фильтрацию списка плагинов по признаку их установки: отображаются либо установленные, либо не установленные плагины (в зависимости от выбранного критерия).</li>
    </ul>
</article>