<?php
/**
 * Страница "Установка плагина".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Installing a plugin</h1>
    <p>The form appears after clicking on the <b>"Install"</b> button on the toolbar <a href="<?= $url('grid') ?>">list of plugins</a>.</p>
    <h2>Form tabs</h2>
    <h3>Tab "Information"</h3>
    <p>The tab displays information about the version, purpose of the plugin, author, and installation requirements.</p>
</article>